apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pts-postgres-db
spec:
  teamId: pts
  postgresql:
    version: "14"
    parameters:
      max_connections: "200"
  numberOfInstances: 1
  volume:
    size: "1Gi"
  users:
    pts:
      - superuser
      - createdb
  databases:
    records: pts
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 200Mi