apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    CREATE TABLE records (
      id                    SERIAL PRIMARY KEY,
      name                  VARCHAR(255) DEFAULT NULL,
      type                  VARCHAR(10) DEFAULT NULL,
      content               VARCHAR(255) DEFAULT NULL,
      ttl                   INT DEFAULT NULL
    );
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-pts-init-job
spec:
  template:
    spec:
      containers:
      - name: init-container
        image: postgres:14
        command: ["/bin/sh", "-c"]
        args: [
          "PGPASSWORD=$(cat /secrets/password) psql -h pts-postgres-db -U $(cat /secrets/username) -d records -f /secrets/init/init.sql",
          "until psql -h pts-postgres-db -U $(cat /secrets/username) -d records -c 'SELECT 1'; do sleep 2; done;",
        ]
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
        - name: configmap-volume
          mountPath: /secrets/init
      restartPolicy: OnFailure
      volumes:
      - name: secret-volume
        secret:
          secretName: postgres.pts-postgres-db.credentials.postgresql.acid.zalan.do
      - name: configmap-volume
        configMap:
          name: init-sql-configmap
