apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-traefik-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-traefik-sync
  template:
    metadata:
      labels:
        app: powerdns-traefik-sync
    spec:
      serviceAccountName: powerdns-traefik-sync-sa
      containers:
      - name: powerdns-traefik-sync
        image: therbert6/pdns-traefik-sync:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        env:
        # PTS tool settings
        - name: PTS_MODE
          value: "standard"
        - name: PTS_DOMAIN_LIST
          value: "all"
        - name: DEBUG_LOGGING
          value: "false"
        - name: SLEEP_DURATION
          value: "45" 

        # PDNS stuff
        - name: PDNS_API_URL
          value: "https://pdns-auth.example.com/api/v1"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: pdns-api-key-secret
              key: PDNS_API_KEY
        - name: PDNS_ZONE_NAME
          value: "example.com"
        - name: TTL
          value: "3600"
        - name: CONTENT
          value: "ingress.example.com."
    
        # PTS database
        - name: PTS_DB_NAME
          value: "pts"      
        - name: PTS_DB_USER
          value: "pts"
        - name: PTS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pts-psql-credentials
              key: PTS_DB_PASSWORD
        - name: PTS_DB_HOST
          value: "postgres-rw.db.svc.cluster.local"       
        - name: PTS_DB_PORT
          value: "5432"       
---
# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: powerdns-traefik-sync-sa
---
# clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressroute-reader
rules:
- apiGroups: ["traefik.containo.us","traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["get", "list", "watch"]
---
# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingressroute-reader-binding
subjects:
- kind: ServiceAccount
  name: powerdns-traefik-sync-sa
  namespace: pdns
roleRef:
  kind: ClusterRole
  name: ingressroute-reader
  apiGroup: rbac.authorization.k8s.io
